server:
  port: 80
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#pageHelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

