server:
  port: 80
#数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
#pagehelper配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#类型转换
mybatis:
  type-handlers-package: com.cskaoyan.project.mall.utils
